ALTER TABLE configuracao ADD COLUMN incluir_pcd INTEGER NOT NULL DEFAULT 0;
ALTER TABLE configuracao ADD COLUMN incluir_mulheres INTEGER NOT NULL DEFAULT 1;
ALTER TABLE vagas ADD COLUMN marcadores TEXT NOT NULL DEFAULT '';
